### ISSUE TITLE
I encountered an unusual error while trying to sign up.

### ISSUE THREAD

**Issue by lightning-sagar** [PorePranav/CampusUnify#1]
![image](https://github.com/user-attachments/assets/3a9a7013-7891-4884-abde-3f94ceeea46d)

pls let me work on this!! pls assign me

**Comment by PorePranav** [comment]
Hi @lightning-sagar,
Thank you for reporting this issue and showing interest in working on it! Please provide a bit more information about the error—such as the steps to reproduce it and any additional logs—so that I can better understand the problem.
Once I have that, I’ll be happy to assign the issue to you. Looking forward to your contributions!

**Comment by lightning-sagar** [comment]
The error may be occurring because the password does not contain any uppercase letters, special symbols, or numbers.

also can u add the hacktober fest tag

**Comment by PorePranav** [comment]
Okay, you may work on it! Just make sure that you adhere to the project's coding style and structure

**Comment by Srijan25** [comment]
is the work done or should i start work on it

**Comment by PorePranav** [comment]
@lightning-sagar Any progress update?

**Comment by lightning-sagar** [comment]
@PorePranav yes bro almost done today I will be making a pr....

**Comment by PorePranav** [comment]
Issue fixed by 50885ed668bf043be2d90ab646d49d210c441a12 , hence closing.
