### ISSUE TITLE
Filters are not working as expected

### ISSUE THREAD

**Issue by Villain45** [PorePranav/CampusUnify#15]
For example: the sort by filter when selected "past" it should show the completed events, but in this case I guess the results are just ordered in descending manner
![image](https://github.com/user-attachments/assets/dadee657-4fd5-44b6-9dbe-a1b3e579f799)
Similarly with the date filter, the events on that particular day should be shown up....

Would like to work on this issue

**Comment by PorePranav** [comment]
Hi @Villain45. Thank you for bringing up the issue to my notice. The issue is that the Sort By should have inputs related to the fields on the event for e.g. date, price etc instead of sorting by ascending or descending. You can change the code to add fields such as date, price to the sort by input and then sort them ascending by default. Assigning the issue to your, make sure that you read the [Contributing Guidelines](https://github.com/PorePranav/CampusUnify/blob/main/CONTRIBUTING.md) before opening up a PR.

**Comment by Villain45** [comment]
Ok, want me to remove the past and upcoming events feature? and what type sort should be for date which you mentioned in the earlier can you elaborate?

**Comment by PorePranav** [comment]
> Ok, want me to remove the past and upcoming events feature? and what type sort should be for date which you mentioned in the earlier comment can you elaborate?

Okay, so what I meant that, you can change the Sort By input to sort 2 fields in the events. So a event basically has fields such as `eventCharges` and a `date`, you can go forward with implementing a functionality where in the Sort By input, a user can select Charges or Date which would then sort the list of events in the view by their `eventCharges` or `date` in a ascending order.

Or if you have an even better idea, you can propose it too.
